export const categories = [
  { id: "cricket", name: "Cricket", icon: "🏏", count: 245, color: "from-green-500 to-emerald-700" },
  { id: "football", name: "Football", icon: "⚽", count: 189, color: "from-blue-500 to-blue-700" },
  { id: "badminton", name: "Badminton", icon: "🏸", count: 132, color: "from-yellow-500 to-orange-600" },
  { id: "tennis", name: "Tennis", icon: "🎾", count: 98, color: "from-lime-500 to-green-600" },
  { id: "gym", name: "Gym & Fitness", icon: "💪", count: 312, color: "from-red-500 to-rose-700" },
  { id: "volleyball", name: "Volleyball", icon: "🏐", count: 76, color: "from-purple-500 to-violet-700" },
  { id: "basketball", name: "Basketball", icon: "🏀", count: 94, color: "from-orange-500 to-red-600" },
  { id: "swimming", name: "Swimming", icon: "🏊", count: 67, color: "from-cyan-500 to-blue-600" },
];

export const products = [
  {
    id: 1,
    name: "Kashmir Willow Cricket Bat Pro",
    category: "cricket",
    price: 3500,
    originalPrice: 4500,
    rating: 4.8,
    reviews: 324,
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500&q=80",
    badge: "Best Seller",
    brand: "DSP",
    inStock: true,
    isNew: false,
    discount: 22,
  },
  {
    id: 2,
    name: "Nike Mercurial Football Size 5",
    category: "football",
    price: 2800,
    originalPrice: 3200,
    rating: 4.7,
    reviews: 198,
    image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=500&q=80",
    badge: "Top Rated",
    brand: "Nike",
    inStock: true,
    isNew: false,
    discount: 13,
  },
  {
    id: 3,
    name: "Yonex Astrox 99 Badminton Racket",
    category: "badminton",
    price: 12500,
    originalPrice: 15000,
    rating: 4.9,
    reviews: 456,
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500&q=80",
    badge: "Premium",
    brand: "Yonex",
    inStock: true,
    isNew: true,
    discount: 17,
  },
  {
    id: 4,
    name: "Wilson Pro Staff Tennis Racket",
    category: "tennis",
    price: 18000,
    originalPrice: 22000,
    rating: 4.8,
    reviews: 289,
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=500&q=80",
    badge: "Pro Choice",
    brand: "Wilson",
    inStock: true,
    isNew: false,
    discount: 18,
  },
  {
    id: 5,
    name: "Adidas Predator Football Boots",
    category: "football",
    price: 8500,
    originalPrice: 11000,
    rating: 4.6,
    reviews: 167,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80",
    badge: "Flash Sale",
    brand: "Adidas",
    inStock: true,
    isNew: false,
    discount: 23,
  },
  {
    id: 6,
    name: "SG Test Cricket Ball Red",
    category: "cricket",
    price: 850,
    originalPrice: 1000,
    rating: 4.7,
    reviews: 512,
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500&q=80",
    badge: "Best Seller",
    brand: "SG",
    inStock: true,
    isNew: false,
    discount: 15,
  },
  {
    id: 7,
    name: "PowerMax Adjustable Dumbbell Set",
    category: "gym",
    price: 15000,
    originalPrice: 18500,
    rating: 4.5,
    reviews: 203,
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=500&q=80",
    badge: "New",
    brand: "PowerMax",
    inStock: true,
    isNew: true,
    discount: 19,
  },
  {
    id: 8,
    name: "Nike Dri-FIT Training Jersey",
    category: "apparel",
    price: 2200,
    originalPrice: 2800,
    rating: 4.6,
    reviews: 389,
    image: "https://images.unsplash.com/photo-1622379888147-2cfbec1c43a4?w=500&q=80",
    badge: "Popular",
    brand: "Nike",
    inStock: true,
    isNew: false,
    discount: 21,
  },
];

export const brands = [
  { id: 1, name: "Nike" },
  { id: 2, name: "Adidas" },
  { id: 3, name: "Yonex" },
  { id: 4, name: "Wilson" },
  { id: 5, name: "DSP" },
  { id: 6, name: "SG" },
  { id: 7, name: "Puma" },
  { id: 8, name: "Reebok" },
];

export const reviews = [
  {
    id: 1,
    name: "Rakib Hassan",
    avatar: "RH",
    rating: 5,
    comment: "Excellent quality products! The cricket bat I ordered is perfect for my game. Fast delivery within 2 days.",
    product: "Kashmir Willow Cricket Bat Pro",
    date: "2 days ago",
    verified: true,
  },
  {
    id: 2,
    name: "Tasnim Akter",
    avatar: "TA",
    rating: 5,
    comment: "The Yonex badminton racket is absolutely worth every taka. My smash power improved dramatically!",
    product: "Yonex Astrox 99 Badminton Racket",
    date: "1 week ago",
    verified: true,
  },
  {
    id: 3,
    name: "Minhaj Uddin",
    avatar: "MU",
    rating: 4,
    comment: "Great platform for sports gear. bKash payment was super smooth. Will definitely order again.",
    product: "Nike Mercurial Football",
    date: "2 weeks ago",
    verified: true,
  },
  {
    id: 4,
    name: "Sadia Islam",
    avatar: "SI",
    rating: 5,
    comment: "The gym equipment quality is outstanding. The adjustable dumbbells are perfect for home workouts.",
    product: "PowerMax Dumbbell Set",
    date: "3 weeks ago",
    verified: true,
  },
];

export const blogPosts = [
  {
    id: 1,
    title: "Top 10 Cricket Bats for Bangladesh Premier League 2025",
    excerpt: "Discover the best cricket bats used by professional cricketers in BPL and how to choose the right one.",
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&q=80",
    category: "Cricket",
    date: "Jun 1, 2025",
    readTime: "5 min read",
  },
  {
    id: 2,
    title: "Complete Guide to Football Nutrition & Training",
    excerpt: "Learn how professional footballers fuel their performance and what training techniques elevate your game.",
    image: "https://images.unsplash.com/photo-1575361204480-aadea25e6e68?w=600&q=80",
    category: "Football",
    date: "May 28, 2025",
    readTime: "7 min read",
  },
  {
    id: 3,
    title: "Building Your Home Gym on a Budget in Bangladesh",
    excerpt: "Transform any room into a professional gym with the right equipment without breaking the bank.",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80",
    category: "Fitness",
    date: "May 20, 2025",
    readTime: "6 min read",
  },
];

export const athletes = [
  {
    id: 1,
    name: "Champion Cricketer",
    sport: "Cricket",
    role: "All-Rounder",
    quote: "GoalGear BD has the best cricket equipment available. The bat quality is truly world-class.",
    initials: "CC",
    product: "DSP Kashmir Willow Pro",
  },
  {
    id: 2,
    name: "Pro Footballer",
    sport: "Football",
    role: "Team Captain",
    quote: "When it comes to football gear, GoalGear BD is my only choice. Authentic products, great service.",
    initials: "PF",
    product: "Nike Mercurial Superfly",
  },
];

export const flashSaleProducts = [
  { ...products[0], flashPrice: 2800, stock: 12, totalStock: 50 },
  { ...products[1], flashPrice: 2240, stock: 8, totalStock: 50 },
  { ...products[2], flashPrice: 10000, stock: 5, totalStock: 30 },
  { ...products[4], flashPrice: 6800, stock: 15, totalStock: 60 },
];

export const formatPrice = (price: number) =>
  `৳${price.toLocaleString("en-BD")}`;
